[package]
name = "basecamp"
version = "0.0.1"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
alexandria_math = "0.6.1"

[dev-dependencies]
cairo_test = "2.12.1"

[cairo]
enable-gas = false
